spring:
  datasource:
    url: jdbc:postgresql://localhost:1212/appdatabase
    username: appadmin
    password: 123456789
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgres
      data-locations: classpath:demo/demodata.sql
  jpa:
    generate-ddl: true
    open-in-view: true
    hibernate:
      ddl-auto: none
  messages:
    basename: exceptions